//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnknownClaimant
    {
        public int Id { get; set; }
        public string Claim8 { get; set; }
        public string ClaimID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> IsForeign { get; set; }
        public string FProv { get; set; }
        public string FZip { get; set; }
        public string FCountry { get; set; }
        public string Email { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneWork { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string SubmitSource { get; set; }
        public string IPAddress { get; set; }
        public string SessionID { get; set; }
        public string UserAgentString { get; set; }
        public Nullable<System.Guid> UploadKey { get; set; }
    }
}
